apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pixlise.fullname" . }}-ui-public
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9113'
    prometheus.io/path: '/metrics'
  labels:
    {{- include "pixlise.labels" . | nindent 4 }}
    {{- include "pixlise.selectorLabels" . | nindent 4 }}-ui-public
    app.kubernetes.io/component: ui
    backstage.io/kubernetes-id: pixlise-ui
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 5 }}
  selector:
    matchLabels:
      {{- include "pixlise.selectorLabels" . | nindent 6 }}-ui-public
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9113'
    {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "pixlise.selectorLabels" . | nindent 8 }}-ui-public
        backstage.io/kubernetes-id: pixlise-ui
    spec:
      containers:
      - name: {{ .Chart.Name  }}-ui-public
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: '100m'
            memory: '100M'
          limits:
            cpu: '500m'
            memory: '500M'
        volumeMounts:
          - name: {{ include "pixlise.fullname" . }}-ui-config-volume
            mountPath: /usr/share/nginx/html/pixlise-config.json
            subPath: pixlise-config.json
      - name: nginx-exporter
        image: 'nginx/nginx-prometheus-exporter:0.11.0'
        args:
          - '-nginx.scrape-uri=http://localhost/nginx_status'
        resources:
          requests:
            cpu: '25m'
            memory: '50M'
          limits:
            cpu: '100m'
            memory: '150M'
        ports:
          - containerPort: 9113
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}

      volumes:
        - name: {{ include "pixlise.fullname" . }}-ui-config-volume
          configMap:
            name: {{ include "pixlise.fullname" . }}-ui-config
