apiVersion: v1
kind: Service
metadata:
  name: {{ include "pixlise.fullname" . }}-ui-public
  labels:
    {{- include "pixlise.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      {{- with .Values.ui.service.nodePort }}
      nodePort: {{ $.Values.ui.service.nodePort }}
      {{- end }}
      targetPort: {{ .Values.ui.service.targetPort }}
      protocol: TCP
      name: {{ .Values.ui.service.name }}-public
  selector:
    {{- include "pixlise.selectorLabels" . | nindent 4 }}-ui-public
