apiVersion: v1
kind: Service
metadata:
  name: {{ include "pixlise.fullname" . }}-core
  labels:
    {{- include "pixlise.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      {{- with .Values.api.service.nodePort }}
      nodePort: {{ $.Values.api.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: {{ .Values.api.service.name }}-core
  selector:
    {{- include "pixlise.selectorLabels" . | nindent 4 }}-core
